# Generated by Django 4.1.5 on 2023-01-19 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('saved_imgs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saved_img',
            name='user',
        ),
    ]
