# Generated by Django 4.1.5 on 2023-01-19 23:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('uploaded_imgs', '0002_uploaded_img_image_alter_uploaded_img_img_name'),
        ('saved_imgs', '0002_remove_saved_img_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='saved_img',
            name='uploaded_img_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='uploaded_imgs.uploaded_img'),
        ),
        migrations.AddField(
            model_name='saved_img',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
