# Generated by Django 4.1.5 on 2023-01-31 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saved_imgs', '0003_saved_img_uploaded_img_id_saved_img_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='saved_img',
            name='image',
            field=models.ImageField(null=True, upload_to='saved_imgs'),
        ),
    ]
