# Generated by Django 4.1.5 on 2023-02-07 18:57

from django.db import migrations, models
import uploaded_imgs.models


class Migration(migrations.Migration):

    dependencies = [
        ('uploaded_imgs', '0003_alter_uploaded_img_upload_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploaded_img',
            name='image',
            field=models.ImageField(null=True, upload_to=uploaded_imgs.models.upload_to),
        ),
    ]
